name: tellify
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pytest
  - pytest-asyncio
  - pandas
  - python-language-server
  - jupyter
  - black
  - redis
  - redis-py
  - aioredis 
  - pip
  - pip:
    - mockaioredis

